### ISSUE TITLE
Requests that doesn't require authentication aren't working.

### ISSUE THREAD

**Issue by filipegiusti** [twitter4r/twitter4r-core#1]
I tried
    Twitter::Client.new().user("twitter_username")

and I got
    NoMethodError: undefined method `[]' for nil:NilClass
        from /usr/lib/ruby/gems/1.8/gems/twitter4r-0.5.0/lib/twitter/client/base.rb:53:in`rest_consumer'
        from /usr/lib/ruby/gems/1.8/gems/twitter4r-0.5.0/lib/twitter/client/base.rb:62:in `rest_access_token'
        from /usr/lib/ruby/gems/1.8/gems/twitter4r-0.5.0/lib/twitter/client/base.rb:16:in`rest_oauth_connect'
        from /usr/lib/ruby/gems/1.8/gems/twitter4r-0.5.0/lib/twitter/client/user.rb:39:in `user'
        from (irb):2

/users/show doesn't require authentication and thus should work this way, right?
I will try to fix this as soon as I have time.

**Comment by mbbx6spp** [comment]
This should now be fixed in bugfix release v0.5.2 just uploaded to Gemcutter.org.

HTH,
Susan

**Comment by filipegiusti** [comment]
Thank you very much!
