### ISSUE TITLE
Deprecated requests for friends and followers

### ISSUE THREAD

**Issue by tomykaira** [twitter4r/twitter4r-core#17]
https://dev.twitter.com/docs/api/1/get/statuses/friends
https://dev.twitter.com/docs/api/1/get/statuses/followers

as these documents say, `/statuses/friends` and `/statuses/followers` are deprecated.

It should be replaced with the new methods, or at least notice this in the document.

**Comment by mbbx6spp** [comment]
Thanks. I will try patching this on my flight this afternoon.
